repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.4.4'
    hooks:
    -   id: autopep8
